language: python
python:
  - 2.7
env:
  - TARGET=test
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -Nqt 5
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/$TARGET
notifications:
  email:
    - franck.ngaha@imio.be
    - simon.delcourt@imio.be
